// Generated by Scripts/sync-layout.py.
public enum PracticeMetadata {
    public static let version = "0.2.1"
    public static let lessonIDs: Set<String> = ["vowels", "rows", "columns", "voiced", "single", "glides", "small", "foreign", "words", "sentences", "special", "migration"]
}
