#!/usr/bin/env python3
"""Import only allowlisted public layout/practice files from a fixed upstream commit.
Usage: python3 Scripts/sync-layout.py --upstream ../wkr-layout --revision <commit>
For local development only, --working-tree marks the pin as uncommitted.
--check compares without writing; no network or private refs are used.
"""
import argparse,datetime,hashlib,json,re,subprocess
from pathlib import Path
root=Path(__file__).resolve().parents[1]
p=argparse.ArgumentParser();p.add_argument('--upstream',required=True);p.add_argument('--revision',default='HEAD');p.add_argument('--working-tree',action='store_true');p.add_argument('--check',action='store_true');p.add_argument('--imported-on',help='ISO date; defaults to the recorded date for the same pin, otherwise today');a=p.parse_args()
u=Path(a.upstream)
revision='uncommitted' if a.working_tree else subprocess.check_output(['git','-C',str(u),'rev-parse',a.revision+'^{commit}'],text=True).strip()
previous_path=root/'Resources/upstream-manifest.json'
previous=json.loads(previous_path.read_text()) if previous_path.exists() else {}
imported_on=a.imported_on or (previous.get('importedOn') if previous.get('revision')==revision else None) or datetime.date.today().isoformat()
datetime.date.fromisoformat(imported_on)
def read(path):
    return (u/path).read_bytes() if a.working_tree else subprocess.check_output(['git','-C',str(u),'show',revision+':'+path])
files=['data/layout-v2.json','docs/layout-v2.md','LICENSE']+['practice/'+n for n in ['index.html','style.css','data.js','core.js','app.js','README.md','VERSION','lessons.json']]
content={f:read(f) for f in files}
spec=json.loads(content['data/layout-v2.json']);rules=spec['rules']
physical=(root/'Sources/WKRCore/WKRTransducer.swift').read_text()
keymap={}
for line in physical.split('public enum BoundaryKey')[0].splitlines():
    m=re.search(r'case (\w+) = "([^"]+)"',line)
    if m:keymap[m[2]]=m[1]
    elif 'case ' in line:
        for name in line.split('case ',1)[1].split(','):keymap[name.strip()]=name.strip()
def quoted(s):return json.dumps(s,ensure_ascii=False)
lines=['// Generated by Scripts/sync-layout.py from the public wkr-layout canonical JSON.',
'public enum WKRLayout {',
'    public static let sourceRepositoryURL = "https://github.com/yuhkis/wkr-layout"',
f'    public static let sourceRevision = {quoted(revision)}',
f'    public static let sourceImportedOn = {quoted(imported_on)}',
f'    public static let layoutVersion = {quoted(spec["version"])}',
'    public static let layoutIdentifier = "wkr-layout@" + sourceRevision',
'    public static let quarantinedUpstreamEntries: [String] = []',
'    public static let symbolLayerProvisionalRomaji: [PhysicalKey: String] = [:]',
'    public static let passThroughKeys = ["[ -> 「", "] -> 」", "Shift+[ -> 『", "Shift+] -> 』"]',
'    public static let rules: [NormalizedRule] = [']
for x in rules:
    fields=f'id: {quoted(x["id"])}, input: ['+', '.join('.'+keymap[k] for k in x['keys'])+']'
    if x['delivery']=='romaji':fields+=f', kana: {quoted(x["output"])}, romaji: {quoted(x["romaji"])}'
    else:fields+=f', text: {quoted(x["output"])}'
    lines.append('        .init('+fields+'),')
lines+=['    ]','    public static let rulesWithoutSymbolLayer = rules.filter { !symbolRuleIDs.contains($0.id) }',
'    private static let symbolRuleIDs: Set<String> = ['+', '.join(quoted(x['id']) for x in rules if x['group']=='symbols')+']',
'    public static let optimisticDeletionProfile = OptimisticDeletionProfile(backspacesByRuleID: [']
prefixes={tuple(x['keys'][:i]) for x in rules for i in range(1,len(x['keys']))}
for x in rules:
    if tuple(x['keys']) in prefixes:lines.append('        '+quoted(x['id'])+': '+str(len(x['output']))+',')
lines+=['    ])','}','']
lessonIDs=[x['id'] for x in json.loads(content['practice/lessons.json'])]
metadata='// Generated by Scripts/sync-layout.py.\npublic enum PracticeMetadata {\n    public static let version = '+quoted(content['practice/VERSION'].decode().strip())+'\n    public static let lessonIDs: Set<String> = ['+', '.join(quoted(x) for x in lessonIDs)+']\n}\n'
outputs={'Sources/WKRCore/WKRLayout.swift':'\n'.join(lines).encode(),'Sources/WKRCore/PracticeMetadata.swift':metadata.encode(),
         'Resources/Layout/layout-v2.json':content['data/layout-v2.json'],
         'docs/layout-reference.md':('# macOSでの配列と綴り\n\n正本: [wkr-layout](https://github.com/yuhkis/wkr-layout)、固定commit `'+revision+'`。\n\n'+content['docs/layout-v2.md'].decode()).encode()}
for path,data in content.items():
    if path.startswith('practice/') and not path.endswith('lessons.json'):outputs['Resources/Practice/'+path.split('/',1)[1]]=data
outputs['Resources/Practice/LICENSE']=content['LICENSE']
manifest={'upstream':'https://github.com/yuhkis/wkr-layout','revision':revision,'importedOn':imported_on,'layoutVersion':spec['version'],'practiceVersion':content['practice/VERSION'].decode().strip(),'files':{f:hashlib.sha256(d).hexdigest() for f,d in content.items()}}
outputs['Resources/upstream-manifest.json']=(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n').encode()
stale=[]
for path,data in outputs.items():
    dest=root/path
    if a.check:
        if not dest.exists() or dest.read_bytes()!=data:stale.append(path)
    else:dest.parent.mkdir(parents=True,exist_ok=True);dest.write_bytes(data)
if stale:raise SystemExit('Sync differs: '+', '.join(stale))
print(f'{len(rules)} rules; layout {spec["version"]}; upstream {revision}; '+('checked' if a.check else 'synced'))
